config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "categories#index"
    resources :categories
    resources :questions
    resources :answers
    resources :users, only: [:index, :destroy]
  end
  root "static_pages#home"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup"  => "users#new"
  resources :users
  resources :categories, only: :index do
    resources :lessons, except: [:new, :index, :destroy]
  end
  resources :results do
    resources :user, only: :index
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lessons
  has_many :results
  has_secure_password
  before_save :downcase_email
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  scope :newest, -> {order created_at: :desc}
  scope :search_condition, ->condition do
    where "name LIKE ? OR email LIKE ?", "%#{condition}%", "%#{condition}%" if condition.present?
  end

  def is_user? user
    self == user
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :load_user, only: :destroy

  def index
    @users = User.search_condition(params[:search]).newest
      .paginate page: params[:page], per_page: Settings.per_page
  end

  def destroy
    if @user.destroy
      flash[:success] = t "admin.user.user_del"
    else
      flash[:danger] = t "admin.user.user_del_fail"
    end
    redirect_to admin_users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update]

  def index
    @users = User.newest.paginate page: params[:page], per_page: Settings.per_page
  end

  def show
    @results = @user.results.correct_anwsers
    @user_lessons = @user.lessons
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "profile_updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "welcome"
      redirect_to @user
    else
      flash[:danger] = t "error_massages"
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password
  end

  def correct_user
    @user = User.find_by id: params[:id]
    unless @user.is_user? current_user
      flash[:danger] = t "access_denied"
      redirect_to :back
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  def gravatar_for user
    image_tag "avatar.png", alt: user.name, class: "gravatar"
  end
end

app/views/users/_user.html.erb
<li>
  <% if user.avatar.nil? %>
    <%= image_tag "avatar.png", class: "gravatar" %>
  <% else %>
    <%= image_tag user.avatar, class: "gravatar" %>
  <% end %>
  <%= link_to user.name, user %><br>
  <%= user.email %>
</li>

app/views/users/edit.html.erb
<div class="col-md-12">
  <div class="box">
    <div class="col-md-6 col-sm-offset-3">
      <h1 class="text-center"><%= t "edit_profile" %></h1>
      <hr>
      <%= form_for @user do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="form-group">
          <%= f.label t "name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label t "email" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label t "password" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, t("password_confirmation") %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <div class="text-center">
          <%= f.submit t("save"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t("all_user") %>
<h1><% t "all_user" %></h1>
<%= will_paginate %>
  <ul class="users">
    <%= render @users %>
  </ul>
<%= will_paginate %>

app/views/users/new.html.erb
<div class="col-md-12 box">
  <div class="box">
    <div class="col-md-6 col-sm-offset-3">
      <h1 class="text-center"><%= t "signup" %></h1>
      <hr>
      <%= form_for @user do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="form-group">
          <%= f.label t("name") %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label t("email") %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label t("password") %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label t("password_confirmation")%>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <div class="text-center">
          <%= f.submit t("create_account"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-sm-12 box container">
  <div class="col-sm-8 col-sm-offset-2">
    <aside class="col-md-6">
      <section class="user_info">
        <p><em><%= gravatar_for @user %></em><br>
        <strong><%= @user.name %></strong><br>
        <code><%= @user.email %></code></p><br>
        <% if @results.length > 0 %>
          <samp><%= t "user_info" %><%= @results.length %> </samp>
          <%= link_to t("words"), result_path(@user) %><br>
          <samp><%= t "user_info" %><%= @user_lessons.length %> <%= t "categories" %></samp><br>
        <% end %>
      </section>
    </aside>
    <aside class="col-md-6 text-center start-lesson">
      <%= link_to t("user_start"), categories_path, class: "btn btn-primary btn-lg"%>
    </aside>
  </div>
</div>