config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "categories#index"
    resources :categories
    resources :questions
    resources :answers
    resources :users, only: [:index, :destroy]
  end
  root "static_pages#home"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup"  => "users#new"
  resources :users
  resources :categories, only: :index do
    resources :lessons, except: [:new, :index, :destroy]
  end
  resources :results do
    resources :user, only: :index
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons
  has_many :questions

  validates :title, presence: true, length: {maximum: 100},
    uniqueness: {case_sensitive: false}
  validates :question_number, presence: true, inclusion: 1..20

  scope :newest, -> {order created_at: :desc}
  scope :search_name, ->name do
    where "title LIKE ?", "%#{name}%" if name.present?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :load_category, only: [:destroy, :update, :edit]

  def index
    @categories = Category.search_name(params[:search]).newest
      .paginate page: params[:page], per_page: Settings.per_page
    @category = Category.new
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "update_category_successfully"
    else
      flash[:danger] = t "update_category_not_successfully"
    end
    redirect_to admin_categories_path
  end

  def create
    @category = Category.new category_params
    if @category.save
      respond_to do |format|
        format.html do
          flash[:success] = t "admin.category.category_successfully"
          redirect_to admin_categories_path
        end
        format.json {render json: @category.to_json}
      end
    else
      flash[:danger] = t "admin.category.category_error_create"
      redirect_to admin_categories_path
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "delete_successfully"
    else
      flash[:danger] = t "delete_not_successfully"
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :title, :question_number
  end

  def load_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t "category_not_exist"
      redirect_to admin_categories_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user, only: :index

  def index
    @categories = Category.newest.paginate page: params[:page],
      per_page: Settings.per_page
    @lesson = Lesson.new
  end
end

app/views/admin/categories/_category.html.erb
<% @categories.each_with_index do |category, index| %>
  <tr>
    <td>#<%= current_index Settings.per_page, index, @categories.current_page %></td>
    <td><%= category.title %></td>
    <td>
      <%= link_to t("edit"), edit_admin_category_path(category.id),
        class: "btn btn-primary btn-sm" %>
    </td>
    <td>
      <%= link_to t("delete"), admin_category_path(category.id), method: :delete,
        class: "btn btn-danger btn-sm", data: {confirm: t("admin.confirm_del")} %>
    </td>
  </tr>
<% end %>

app/views/admin/categories/_create.html.erb
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog"
  aria-labelledby="Create" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
          aria-hidden="true">&times;</button>
        <h4 class="modal-title text-center"><%= t "new_category" %></h4>
      </div>
      <%= form_for [:admin, @category], remote: true do |f| %>
        <%= render "admin/shared/error_messages", object: f.object %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.text_field :title, class: "form-control",
              placeholder: t("admin.category.new_category") %>
          </div>
          <div class="form-group">
            <%= f.number_field :question_number, class: "form-control",
              placeholder: t("admin.category.question_number") %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit t("create"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<div class="col-sm-12">
  <ul class="breadcrumb">
    <li><%= link_to t("admin.manage"), admin_root_path %></li>
    <li><%= t "catrgories" %></li>
  </ul>
</div>
<%= render "admin/layouts/left_bar" %>
<div class="col-sm-9">
  <div class="row box">
    <div class="col-md-6 col-md-offset-3">
    <h1><%= t "edit_category" %></h1>
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :question_number %>
        <%= f.number_field :question_number, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit t("save_changes"), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="col-sm-12">
  <ul class="breadcrumb">
    <li><%= link_to t("admin.manage"), admin_root_path %></li>
    <li><%= t "catrgories" %></li>
  </ul>
</div>
<%= render "admin/layouts/left_bar" %>
<div class="col-sm-9">
  <div class="row box">
   <div class="col-sm-12 nopadding">
      <div class="col-sm-5">
        <h3><%= t "categories" %></h3>
      </div>
      <div class="col-sm-7">
        <div class="col-sm-4 nopadding">
          <%= link_to t("add_new"), "#", class: "btn btn-primary",
            data: {toggle: "modal", target: "#create-modal"}%>
        </div>
        <div class="col-sm-8">
          <%= form_tag admin_categories_path, method: :get, id: "admin_search", class: "row" do %>
            <%= render "admin/shared/form_search" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-12">
      <div class="table-bordered">
        <table class="table table-striped">
          <thead>
            <tr>
              <th><%= t "categories" %></th>
              <th colspan="3"><%= t "title_category" %></th>
            </tr>
          </thead>
          <tbody id="result_search">
            <%= render "category" %>
          </tbody>
        </table>
      </div>
      <div class="pull-right">
        <%= will_paginate @categories %>
      </div>
    </div>
  </div>
</div>
<%= render "create" %>

app/views/admin/categories/index.js.erb
$('#result_search').html('<%= j render "category" %>');