config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "categories#index"
    resources :categories
    resources :questions
    resources :answers
    resources :users, only: [:index, :destroy]
  end
  root "static_pages#home"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup"  => "users#new"
  resources :users
  resources :categories, only: :index do
    resources :lessons, except: [:new, :index, :destroy]
  end
  resources :results do
    resources :user, only: :index
  end
end

app/views/admin/layouts/_left_bar.html.erb
<div class="col-sm-3">
  <div class="panel panel-default sidebar-menu">
    <div class="panel-heading">
      <h3 class="panel-title"><%= t "manage" %></h3>
    </div>
    <div class="panel-body">
      <ul class="nav nav-pills nav-stacked">
        <li class="<%= active_class admin_root_path %>">
          <%= link_to admin_root_path do %>
            <span class="glyphicon glyphicon-home"></span>
            <%= t "home" %>
          <% end %>
        </li>
        <li class="<%= active_class admin_categories_path %>">
          <%= link_to admin_categories_path do %>
            <span class="glyphicon glyphicon-th-list"></span>
            <%= t "categories" %>
          <% end %>
        </li>
        <li class="<%= active_class admin_users_path %>">
          <%= link_to admin_users_path do %>
            <span class="glyphicon glyphicon-user"></span>
            <%= t "users" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>