config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "categories#index"
    resources :categories
    resources :questions
    resources :answers
    resources :users, only: [:index, :destroy]
  end
  root "static_pages#home"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "signup"  => "users#new"
  resources :users
  resources :categories, only: :index do
    resources :lessons, except: [:new, :index, :destroy]
  end
  resources :results do
    resources :user, only: :index
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lessons
  has_many :results
  has_secure_password
  before_save :downcase_email
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  scope :newest, -> {order created_at: :desc}
  scope :search_condition, ->condition do
    where "name LIKE ? OR email LIKE ?", "%#{condition}%", "%#{condition}%" if condition.present?
  end

  def is_user? user
    self == user
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :load_user, only: :destroy

  def index
    @users = User.search_condition(params[:search]).newest
      .paginate page: params[:page], per_page: Settings.per_page
  end

  def destroy
    if @user.destroy
      flash[:success] = t "admin.user.user_del"
    else
      flash[:danger] = t "admin.user.user_del_fail"
    end
    redirect_to admin_users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update]

  def index
    @users = User.newest.paginate page: params[:page], per_page: Settings.per_page
  end

  def show
    @results = @user.results.correct_anwsers
    @user_lessons = @user.lessons
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "profile_updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "welcome"
      redirect_to @user
    else
      flash[:danger] = t "error_massages"
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password
  end

  def correct_user
    @user = User.find_by id: params[:id]
    unless @user.is_user? current_user
      flash[:danger] = t "access_denied"
      redirect_to :back
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  def gravatar_for user
    image_tag "avatar.png", alt: user.name, class: "gravatar"
  end
end

app/views/admin/users/_user.html.erb
<% @users.each_with_index do |user, index| %>
  <tr>
    <td>
      #<%= current_index Settings.per_page, index,
        @users.current_page %>
    </td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td>
      <% unless current_user.is_user? user %>
        <%= link_to t("delete"), admin_user_path(user.id), method: :delete,
          class: "btn btn-danger btn-sm", data: {confirm: t("admin.confirm_del")} %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/admin/users/index.html.erb
<div class="col-sm-12">
  <ul class="breadcrumb">
    <li><%= link_to t("home"), admin_root_path %></li>
    <li><%= t "users" %></li>
  </ul>
</div>
<%= render "admin/layouts/left_bar" %>
<div class="col-sm-9">
  <div class="row box">
    <div class="col-sm-12">
      <h3 class="pull-left"><%= t "users" %></h3>
      <div class="pull-right">
        <%= form_tag admin_users_path, method: :get, id: "admin_search" do %>
          <%= render "admin/shared/form_search" %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-12">
      <div class="table-bordered">
        <table class="table table-striped">
          <thead>
            <tr>
              <th><%= t "users" %></th>
              <th><%= t "name" %></th>
              <th colspan="2"><%= t "email" %></th>
            </tr>
          </thead>
          <tbody id="result_search">
            <%= render "user" %>
          </tbody>
        </table>
      </div>
      <div class="pull-right">
        <%= will_paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.js.erb
$('#result_search').html('<%= j render "user" %>');